export const priceList=
{
"Cabbage Soup (Shchi)":199,
 "Cacik":189,
 "Cajun spiced fish tacos":250,
 "Callaloo and SaltFish":299,
 "Callaloo Jamaican Style":250,
 "Canadian Butter Tarts":350,
 "Carbonada Criolla":250,
 "Caribbean Tamarind balls":399,
 "Carrot Cake":150,
 "Cashew Ghoriba Biscuits":199,
 "Cassava pizza":250,
 "Cevapi Sausages":289,
 "Chakchouka":199,
 "Challah":280,
 "Cheese Borek":350,
 "Chelsea Buns":300,
 "Chick-Fil-A Sandwich":290,
 "Chicken & chorizo rice pot":260,
 "Chicken & mushroom Hotpot":290,
 "Chicken Alfredo Primavera":389,
"Chicken Basquaise":270,
 "Chicken Congee":320,
  "Chicken Couscous":240,
  "Chicken Enchilada Casserole":310,
"Chicken Fajita Mac and Cheese":390,
"Chicken Fried Rice":250,
"Chicken Ham and Leek Pie":250,
"Chicken Handi":330,
"Chicken Karaage":320,
"Chicken Mandi":240,
"Chicken Marengo":250,
"Chicken Parmentier":260,
"Chicken Quinoa Greek Salad":199,
"Chicken Shawarma with homemade garlic herb yoghurt sauce":189,
"Chicken wings with cumin, lemon & garlic":280,
"Chicken with saffron, raisins & pine nuts":299,
"Chickpea Fajitas":190,
"Chickpea, chorizo & spinach stew":280,
"Chilli ginger lamb chops":299,
"Chilli prawn linguine":270,
"Chinese Orange Chicken":270,
"Chinese Tomato Egg Stir Fry":199,
"Chinon Apple Tarts":280,
"Chivito sandwich":190,
"Chivito uruguayo":698,
"Choc Chip Pecan Pie":190,
"Chocolate alfajores":190,
"Chocolate Avocado Mousse":200,
"Chocolate Caramel Crispy":290,
"Chocolate churros with chocolate & salted caramel sauce":390,
"Chocolate Coconut Squares":189,
"Chocolate empanadas":250,
"Chocolate Gateau":350,
"Chocolate Raspberry Brownies":260,
"Chocolate Souffle":340,
"Chorba Hamra bel Frik (Algerian Lamb, Tomato, and Freekeh Soup)":170,
"Choripán":260,
"Chorizo & chickpea soup":289,
"Chorizo & soft-boiled egg salad":279,
"Chorizo & tomato salad":189,
"Chorizo, potato & cheese omelette":340,
"Christmas cake":360,
"Christmas Pudding Flapjack":220,
"Christmas Pudding Trifle":290,
"Chtitha Batata (Algerian Potato Stew)":200,
"Churros":160,
"Cinnamon buns":170,
"Clam chowder":290,
"Clam, chorizo & white bean stew":180,
"Classic Christmas pudding":250,
"Classic Tourtière":289,
"Coddled pork with cider":289,
"Coq au vin":190,
"Corba":230,
"Corned Beef and Cabbage":340,
"Corned Beef and Cabbage – Jamaican Style":350,
"Corned Beef Hash":380,
"Cornes de Gazelle (Gazelle Horns)":340,
"Cream Cheese Tart":299,
"Creamy Tomato Soup":359,
"Crema Catalana":369,
"Crispy Eggplant":349,
"Crispy Sausages and Greens":289,
"Croatian Bean Stew":279,
"Croatian lamb peka":287,
"Crock Pot Chicken Baked Tacos":354,
"Cucumber & fennel salad":199,
 "Cumberland Pie":289

}